[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "journey puzzle essence check chuckle possible dinosaur address panic more disorder erupt next spare canal accuse aim riot poet daring dream atom online network
"
